package youtube

import (
	"net/http"
	"net/url"
)

const (
	VideoAdvertisingOptionsUrl = YoutubePartnerV1 + "/videoAdvertisingOptions"
)

// VideoAdvertisingOption contains information about the advertising settings
// for a specific video, including ad formats, break positions, and
// third-party ad server configuration.
//
// see https://developers.google.com/youtube/partner/reference/rest/v1/videoAdvertisingOptions#VideoAdvertisingOption
type VideoAdvertisingOption struct {
	// AdBreaks is a list of ad breaks configured for the video. Each ad break
	// specifies a point in the video where an ad can be inserted.
	AdBreaks []*AdBreak `json:"adBreaks,omitempty"`
	// AdFormats is a list of ad formats that the video supports (e.g.,
	// "long", "overlay", "trueview_instream").
	AdFormats []string `json:"adFormats,omitempty"`
	// AutoGeneratedBreaks indicates whether ad breaks are automatically
	// generated for the video.
	AutoGeneratedBreaks bool `json:"autoGeneratedBreaks,omitempty"`
	// BreakPosition is a list of positions where ad breaks can be inserted
	// (e.g., "preroll", "postroll", "midroll").
	BreakPosition []string `json:"breakPosition,omitempty"`
	// Id is the YouTube video ID associated with these advertising options.
	Id string `json:"id,omitempty"`
	// Kind identifies the API resource type. The value is "youtubePartner#videoAdvertisingOption".
	Kind string `json:"kind,omitempty"`
	// TpAdServerVideoId is the third-party ad server video ID used to identify
	// the video on the ad server.
	TpAdServerVideoId string `json:"tpAdServerVideoId,omitempty"`
	// TpTargetingUrl is the URL used for third-party ad server targeting.
	TpTargetingUrl string `json:"tpTargetingUrl,omitempty"`
	// TpUrlParameters contains additional URL parameters to send to the
	// third-party ad server.
	TpUrlParameters string `json:"tpUrlParameters,omitempty"`
}

// VideoAdvertisingOptionGetEnabledAdsResponse is the response for
// videoAdvertisingOptions.getEnabledAds. It describes which ad types are
// actually enabled for a specific video, taking into account content owner
// settings and country restrictions.
type VideoAdvertisingOptionGetEnabledAdsResponse struct {
	// AdBreaks is a list of ad breaks enabled for the video.
	AdBreaks []*AdBreak `json:"adBreaks,omitempty"`
	// AdsOnEmbeds indicates whether ads are enabled on embedded players.
	AdsOnEmbeds bool `json:"adsOnEmbeds,omitempty"`
	// CountriesRestriction is a list of country-specific ad restrictions.
	CountriesRestriction []*CountriesRestriction `json:"countriesRestriction,omitempty"`
	// Id is the YouTube video ID.
	Id string `json:"id,omitempty"`
	// Kind identifies the API resource type. The value is "youtubePartner#videoAdvertisingOptionGetEnabledAds".
	Kind string `json:"kind,omitempty"`
}

// ── videoAdvertisingOptions.get ─────────────────────────────────────────────

// GetVideoAdvertisingOptionParams are parameters for videoAdvertisingOptions.get.
type GetVideoAdvertisingOptionParams struct {
	// VideoId is the YouTube video ID of the video for which to retrieve
	// advertising settings.
	VideoId string
	// OnBehalfOfContentOwner identifies the content owner that the user is
	// acting on behalf of. This parameter supports users whose accounts are
	// associated with multiple content owners.
	OnBehalfOfContentOwner string
}

func (p *GetVideoAdvertisingOptionParams) Values() url.Values {
	v := url.Values{}
	if p.OnBehalfOfContentOwner != "" {
		v.Set("onBehalfOfContentOwner", p.OnBehalfOfContentOwner)
	}
	return v
}

// GetVideoAdvertisingOption retrieves the advertising settings for the
// specified video. These settings include ad formats, break positions, and
// third-party ad server configuration.
//
// see https://developers.google.com/youtube/partner/reference/rest/v1/videoAdvertisingOptions/get
func GetVideoAdvertisingOption(runner RequestRunner, p *GetVideoAdvertisingOptionParams) (*VideoAdvertisingOption, error) {
	res, err := runner.Run(&Request{
		Method: http.MethodGet,
		Url:    VideoAdvertisingOptionsUrl + "/" + p.VideoId,
		Params: p.Values(),
	})
	if err != nil {
		return nil, err
	}
	var out VideoAdvertisingOption
	if err := DecodeResponse(res, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ── videoAdvertisingOptions.getEnabledAds ───────────────────────────────────

// GetEnabledAdsParams are parameters for videoAdvertisingOptions.getEnabledAds.
type GetEnabledAdsParams struct {
	// VideoId is the YouTube video ID of the video for which to retrieve
	// enabled ad types.
	VideoId string
	// OnBehalfOfContentOwner identifies the content owner that the user is
	// acting on behalf of. This parameter supports users whose accounts are
	// associated with multiple content owners.
	OnBehalfOfContentOwner string
}

func (p *GetEnabledAdsParams) Values() url.Values {
	v := url.Values{}
	if p.OnBehalfOfContentOwner != "" {
		v.Set("onBehalfOfContentOwner", p.OnBehalfOfContentOwner)
	}
	return v
}

// GetEnabledAds retrieves details about the types of ads that are actually
// enabled for a specified video. The response indicates which ad types are
// allowed based on the video's advertising settings and any country-specific
// restrictions.
//
// see https://developers.google.com/youtube/partner/reference/rest/v1/videoAdvertisingOptions/getEnabledAds
func GetEnabledAds(runner RequestRunner, p *GetEnabledAdsParams) (*VideoAdvertisingOptionGetEnabledAdsResponse, error) {
	res, err := runner.Run(&Request{
		Method: http.MethodGet,
		Url:    VideoAdvertisingOptionsUrl + "/" + p.VideoId + "/getEnabledAds",
		Params: p.Values(),
	})
	if err != nil {
		return nil, err
	}
	var out VideoAdvertisingOptionGetEnabledAdsResponse
	if err := DecodeResponse(res, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ── videoAdvertisingOptions.patch ───────────────────────────────────────────

// PatchVideoAdvertisingOptionParams are parameters for videoAdvertisingOptions.patch.
type PatchVideoAdvertisingOptionParams struct {
	// VideoId is the YouTube video ID of the video for which to patch
	// advertising settings.
	VideoId string
	// OnBehalfOfContentOwner identifies the content owner that the user is
	// acting on behalf of. This parameter supports users whose accounts are
	// associated with multiple content owners.
	OnBehalfOfContentOwner string
	// Option is the VideoAdvertisingOption resource with updated fields.
	Option *VideoAdvertisingOption
}

func (p *PatchVideoAdvertisingOptionParams) Values() url.Values {
	v := url.Values{}
	if p.OnBehalfOfContentOwner != "" {
		v.Set("onBehalfOfContentOwner", p.OnBehalfOfContentOwner)
	}
	return v
}

// PatchVideoAdvertisingOption patches the advertising settings for a video.
// This method supports patch semantics, meaning only the fields included in the
// request body will be updated; all other fields will retain their current values.
//
// see https://developers.google.com/youtube/partner/reference/rest/v1/videoAdvertisingOptions/patch
func PatchVideoAdvertisingOption(runner RequestRunner, p *PatchVideoAdvertisingOptionParams) (*VideoAdvertisingOption, error) {
	body, err := jsonBody(p.Option)
	if err != nil {
		return nil, err
	}
	res, err := runner.Run(&Request{
		Method: http.MethodPatch,
		Url:    VideoAdvertisingOptionsUrl + "/" + p.VideoId,
		Params: p.Values(),
		Body:   body,
	})
	if err != nil {
		return nil, err
	}
	var out VideoAdvertisingOption
	if err := DecodeResponse(res, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ── videoAdvertisingOptions.update ──────────────────────────────────────────

// UpdateVideoAdvertisingOptionParams are parameters for videoAdvertisingOptions.update.
type UpdateVideoAdvertisingOptionParams struct {
	// VideoId is the YouTube video ID of the video for which to update
	// advertising settings.
	VideoId string
	// OnBehalfOfContentOwner identifies the content owner that the user is
	// acting on behalf of. This parameter supports users whose accounts are
	// associated with multiple content owners.
	OnBehalfOfContentOwner string
	// Option is the complete VideoAdvertisingOption resource to replace the
	// existing advertising settings.
	Option *VideoAdvertisingOption
}

func (p *UpdateVideoAdvertisingOptionParams) Values() url.Values {
	v := url.Values{}
	if p.OnBehalfOfContentOwner != "" {
		v.Set("onBehalfOfContentOwner", p.OnBehalfOfContentOwner)
	}
	return v
}

// UpdateVideoAdvertisingOption updates the advertising settings for a video.
// This method replaces the entire resource, so all fields must be provided.
// Use PatchVideoAdvertisingOption for partial updates.
//
// see https://developers.google.com/youtube/partner/reference/rest/v1/videoAdvertisingOptions/update
func UpdateVideoAdvertisingOption(runner RequestRunner, p *UpdateVideoAdvertisingOptionParams) (*VideoAdvertisingOption, error) {
	body, err := jsonBody(p.Option)
	if err != nil {
		return nil, err
	}
	res, err := runner.Run(&Request{
		Method: http.MethodPut,
		Url:    VideoAdvertisingOptionsUrl + "/" + p.VideoId,
		Params: p.Values(),
		Body:   body,
	})
	if err != nil {
		return nil, err
	}
	var out VideoAdvertisingOption
	if err := DecodeResponse(res, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
